const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
    saveFormData: (data) => ipcRenderer.send('save-form-data', data),
    getPills: () => ipcRenderer.send('get-pills'),
    updatePill: (data) => ipcRenderer.send('updatePill', data),
    deletePill: (id) => ipcRenderer.send('deletePill', id),
    onGetPillsResponse: (callback) => ipcRenderer.on('get-pills-response', (_event, pills) => callback(pills)),
    onSaveResponse: (callback) => ipcRenderer.on('save-form-data-response', (_event, message) => callback(message)),
    onDeletePillResponse: (callback) => ipcRenderer.on('delete-pill-response', (_event, message) => callback(message)),
    windowMinimize: () => ipcRenderer.invoke('window:minimize'),
    windowMaximizeToggle: () => ipcRenderer.invoke('window:maximizeToggle'),
    windowClose: () => ipcRenderer.invoke('window:close'),
    expandWindowForRect: (rect) => ipcRenderer.invoke('window:expandForRect', rect),
    restorePopoverBounds: () => ipcRenderer.invoke('window:restorePopoverBounds'),
    setContentMinHeight: (height) => ipcRenderer.invoke('window:setContentMinHeight', height),
    onPopoverReset: (callback) => ipcRenderer.on('window:popover-reset', () => callback()),
    onWindowState: (callback) => ipcRenderer.on('window:state', (_event, state) => callback(state)),
    onAlarmRing: (callback) => ipcRenderer.on('alarm:ring', (_event, payload) => callback(payload)),
    onAlarmStop: (callback) => ipcRenderer.on('alarm:stop', () => callback()),
    snoozeAlarm: (payload) => ipcRenderer.invoke('alarm:snooze', payload),
    dismissAlarm: () => ipcRenderer.invoke('alarm:dismiss'),
    testAlarm: (delaySeconds = 0) => ipcRenderer.invoke('alarm:test', delaySeconds),
    isDev: () => ipcRenderer.invoke('app:isDev'),
    getSettings: () => ipcRenderer.invoke('settings:get'),
    setSettings: (patch) => ipcRenderer.invoke('settings:set', patch),
    getAlertStatus: () => ipcRenderer.invoke('settings:alertStatus'),
    requestAlertPermission: (kind) => ipcRenderer.invoke('settings:requestAlertPermission', kind),
    addCustomSound: () => ipcRenderer.invoke('settings:addCustomSound'),
    removeCustomSound: (soundId) => ipcRenderer.invoke('settings:removeCustomSound', soundId),
    onSettingsChanged: (callback) => ipcRenderer.on('settings:changed', (_event, settings) => callback(settings)),
    getAppVersion: () => ipcRenderer.invoke('update:getVersion'),
    checkForUpdates: () => ipcRenderer.invoke('update:check'),
    downloadUpdate: () => ipcRenderer.invoke('update:download'),
    installUpdate: () => ipcRenderer.invoke('update:install'),
    openReleases: () => ipcRenderer.invoke('update:openReleases'),
    onUpdateStatus: (callback) => ipcRenderer.on('update:status', (_event, status) => callback(status)),
});
